IBM/cp4mcm-samples

- CHANGELOG.md
- scripts/cp4mcm-cleanup-utility.sh
https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/10569
https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/10605
The following script aids the customer in deleting CP4MCM resources that must be deleted prior to uninstalling the Installation instance, and those that should be deleted after uninstalling the Installation instance. Execute the script without any arguments to get a rundown of how to use it.
> Cp4mcm 10569 10605

- scripts/cp4mcm-cleanup-utility.sh
Another resource needed to be cleaned up. Ref: cp4mcm issue #10605
> Added deletion of route; checking errors in postUninstall mode

- CHANGELOG.md
- scripts/ma-prereq-offline.sh
1. Add script for ma preraqs offline case 
2. Support --debug-image option
> Add offline script and new --debug-image option

- CHANGELOG.md
- scripts/cp4mcm-enable-ha.sh
- scripts/cp4mcm-ha-utility.sh
https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/11519
The following script aids the customer to enable HA for CP4MCM. Execute the script with --help to get a rundown of how to use it.
```console
Usage ./cp4mcm-ha-utility.sh
Use this script to enable or diable HA for IBM Cloud Pak for Multicloud Management
Flags:
--kubeconfigPath                 The absolute path to the kubeconfig file to access the cluster. Use default kubeconfig if it is omitted
--list                           List the modules that support HA
--enable                         Enable HA for all modules, or a particular module if --module is specified
--disable                        Disable HA for all modules, or a particular module if --module is specified
--verify                         Verify the results by …
```
> [WIP] CP4MCM 11519

- scripts/im-config-podified.sh
Configures IM with CP 2.0
-OIDC
- Nav links
- Operator Connection
- Access Token support
> Infrastructure Management Script

- CHANGELOG.md
- scripts/cnmon/uninstall_cnmon.sh
- scripts/cp4mcm-rhacm21-cp-issuer-secret.sh
for RHACM 2.1, it needs to copy the issuer secret to the open-cluster-management-issuer namespace as a workaround.
> add rhacm21 issuer secret workaround script

- scripts/cp4mcm-rhacm21-cp-issuer-secret.sh
cp4mcm-issuer-script add msg output
> cp4mcm-issuer-script add msg output

- scripts/ma-prereq.sh
> Fix arch judgement error

- CHANGELOG.md
- scripts/cp4mcm-cleanup-utility.sh
make cp4mcm-cleanup-utility.sh less aggressive; leave odlm and CS when using postUninstallMode; add new mode for just cleaning up secrets/configmaps
> cp4mcm-cleanup-utility.sh improvements

- scripts/cnmon/uninstall_cnmon.sh
verified the script works for both 2.1 and 2.2
> upload uninstall_cnmon.sh for 2.2 release

- scripts/cnmon/uninstall_cnmon.sh
> add logic to delete ua job pod

- scripts/ma-prereq.sh
Fix install failed in latest OCP 4.6.x
> Fix install failed in latest OCP 4.6.x

- chatops-update.sh
Added the script chatops-update.sh to help customer update integration settings for Chatops.
> Added script to update chatops integration setting

- CHANGELOG.md
- scripts/backupcouch.sh
- scripts/restorecouch.sh
Add CouchDB backup/restore scripts to samples repo.
> cp4mcm 2.2 couch b/r scripts

- scripts/chatops-update.sh
add oc login checking for issue 17846
> add oc login checking

- ganesha-nfs-server/base/clusterrole.yaml
- ganesha-nfs-server/base/clusterrolebinding.yaml
- ganesha-nfs-server/base/deployment.yaml
- ganesha-nfs-server/base/kustomization.yaml
- ganesha-nfs-server/base/psp.yaml
- ganesha-nfs-server/base/pvc.yaml
- ganesha-nfs-server/base/role.yaml
- ganesha-nfs-server/base/rolebinding.yaml
- ganesha-nfs-server/base/scc.yaml
- ganesha-nfs-server/base/service.yaml
- ganesha-nfs-server/base/serviceaccount.yaml
- ganesha-nfs-server/base/storageclass.yaml
- ganesha-nfs-server/overlays/size-100gi/kustomization.yaml
- ganesha-nfs-server/overlays/size-100gi/pvc-100.yaml
- ganesha-nfs-server/overlays/size-60gi/kustomization.yaml
- ganesha-nfs-server/overlays/size-60gi/pvc-60.yaml
https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/16687
> Adding ganesha-nfs-server directory; this will be accompanied by a KC doc

- scripts/cnmon/2.3/install_cnmon_offline.sh
- scripts/cnmon/2.3/operator.yaml
> Cnmon script

- CHANGELOG.md
- scripts/grc-policy-updates.sh
Updated `scripts/grc-policy-updates.sh` to be consitent with RHACM
https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/17180
> Updated scripts/grc-policy-updates.sh

- CHANGELOG.md
- vaultfeeder/LICENSE
- vaultfeeder/MAINTAINERS.md
- vaultfeeder/README.md
- vaultfeeder/setup.py
- vaultfeeder/vaultfeeder/vaultfeeder.py
vaultfeeder tool to configure HashiCorp Vault and push target VM credentials in it for IBM CloudPak for Multicloud Management VM policy controller 2.0 onwards.
https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/12954
> Vaultfeeder

- bcdr/backup/README.md
- bcdr/backup/scripts/install-velero-config.json
- bcdr/backup/scripts/install-velero.sh
- bcdr/restore/README.md
- Added script to install `Velero` on OpenShift cluster
- Updated Backup README with install `Velero` steps and also enhanced the content to make it more user friendly 
- Updated Backup README with details of component that get backed up during automated or on-demand backup
- Enhanced the content of Restore README to make it more user friendly
> Updated Backup & Restore README

- bcdr/backup/scripts/cs/dummy-db-airgap.yaml
- bcdr/backup/scripts/cs/dummy-db.yaml
- bcdr/restore/scripts/cs/dummy-db-airgap.yaml
- bcdr/restore/scripts/cs/dummy-db.yaml
Removed securityContext from dummy db YAMLs as it is not required for quay.io/bitnami/nginx:latestimage
> Removed SecurityContext

- scripts/cnmon/2.3/operator.yaml
> 2.3.10 images

- bcdr/backup/README.md
- bcdr/backup/helm/templates/backup-metadata.yaml
- bcdr/backup/helm/templates/backup-ns.yaml
- bcdr/backup/scripts/main.sh
- bcdr/backup/scripts/remove-annotation-from-pvc.sh
- bcdr/backup/scripts/trigger-backup.sh
- bcdr/install/InstallVeleroOnAirgap.md
- bcdr/install/VeleroInstallation.md
- bcdr/install/scripts/install-velero-on-airgap.sh
- bcdr/install/scripts/install-velero.sh
- Added YAMLs for backup Namespace and backup-metadata ConfigMap.
- Removed `RemoveAnnotationFromPVC` function definition from trigger-backup.sh and added in `remove-annotation-from-pvc.sh` file.
- Refactored `main.sh` file, Moved the `Pre Monitoring` task just before the `Trigger Backup` task.
- Updated log statements in Install Velero scripts.
- Updated velero installation command to run in background in both Online & Offline Velero installation documents.
- Updated troubleshooting section.
> Updated Backup scripts and documentation

- bcdr/backup/scripts/backup_original.yaml
- bcdr/backup/scripts/cs/dummy-db-airgap.yaml
- bcdr/backup/scripts/cs/dummy-db.yaml
- bcdr/backup/scripts/cs/mongo-image-policy.yaml
- bcdr/backup/scripts/cs/mongodb-dump.yaml
- bcdr/backup/scripts/cs/nginx-image-policy.yaml
- bcdr/restore/scripts/cs/dummy-db-airgap.yaml
- bcdr/restore/scripts/cs/dummy-db.yaml
- bcdr/restore/scripts/cs/mongo-restore-dbdump.yaml
- Updated Security Context in dummy DB YAML's for both backup & restore 
- Added copyright text in few YAML's
> Updated Security Context in backup & restore yamls

- bcdr/restore/RestoreAllComponents.md
- bcdr/restore/RestoreIndividualComponent.md
- bcdr/restore/scripts/restore.sh
- Restore script modified, added script to restore backup config
- Restore doc modified, added some more points in prereq and notes section
- Added step for adding catalog source in Installation section
> Restore script and docs modified 

- CHANGELOG.md
- scripts/cp4mcm-ha-utility.sh
Add the following modules to cp4mcm-ha-utility.sh
- infrastructure-management-vm
- infrastructure-management-grc
> Add infrastructure-management-vm and grc to cp4mcm-ha-utility.sh

- bcdr/backup/scripts/cs/create-mongo-dump.sh
- bcdr/backup/scripts/cs/mongodb-dump.yaml
- Added dynamic wait after old resource deletion
> Fix for issue 21850

- scripts/ma-prereq-offline.sh
The OpenShift Container Platform 4.12 release fixes an issue with entering a debug session on a target node when the target namespace lacks the appropriate security level. This caused the oc CLI to prompt you with a pod security error message. If the existing namespace does not contain the appropriate security levels, OpenShift Container Platform now creates a temporary namespace when you enter oc debug mode on a target node. (OCPBUGS-852)
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/release_notes/ocp-4-12-release-notes#ocp-4-12-bug-fixes
> Adapt MA prerequisite script to work in OCP 4.12 environment
